font_family      MesloLGM Nerd Font Regular
bold_font        MesloLGM Nerd Font Bold
italic_font      MesloLGM Nerd Font Italic
bold_italic_font MesloLGM Nerd Font Bold Italic
font_size 14.0
background #34343b
